version: '3'

services:
  db:
    image: spartakode/sqlite3:latest
    volumes:
      - . db.sqlite3
  web:
    build: .
    expose:
      - 8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
       - db